version: "3.5"

services:

  cert-gen:
    image: docker.pkg.github.com/eventstore/es-gencert-cli/es-gencert-cli:1.0.1
    entrypoint: bash
    command: >
      -c "es-gencert-cli create-ca -out /tmp/ca &&
          es-gencert-cli create-node -ca-certificate /tmp/ca/ca.crt -ca-key /tmp/ca/ca.key -out \
          /tmp/node1 -ip-addresses 127.0.0.1,172.30.240.11 &&
          es-gencert-cli create-node -ca-certificate /tmp/ca/ca.crt -ca-key /tmp/ca/ca.key -out \
          /tmp/node2 -ip-addresses 127.0.0.1,172.30.240.12 &&
          es-gencert-cli create-node -ca-certificate /tmp/ca/ca.crt -ca-key /tmp/ca/ca.key -out \
          /tmp/node3 -ip-addresses 127.0.0.1,172.30.240.13"
    volumes:
      - "./certs:/tmp"

  esdb-node1:
    image: docker.pkg.github.com/eventstore/eventstore/eventstore:20.6.1-alpha.0.54-buster-slim
    env_file:
      - shared.env
    environment:
      - EVENTSTORE_GOSSIP_SEED=172.30.240.12:2113,172.30.240.13:2113
      - EVENTSTORE_INT_IP=172.30.240.11
      - EVENTSTORE_CERTIFICATE_FILE=/certs/node1/node.crt
      - EVENTSTORE_CERTIFICATE_PRIVATE_KEY_FILE=/certs/node1/node.key
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=127.0.0.1
      - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2111
      - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=1111
    ports:
      - 1111:1113
      - 2111:2113
    networks:
      clusternetwork:
        ipv4_address: 172.30.240.11
    volumes:
      - ./certs:/certs
    restart: unless-stopped
    depends_on:
      - cert-gen

  esdb-node2:
    image: docker.pkg.github.com/eventstore/eventstore/eventstore:20.6.1-alpha.0.54-buster-slim
    env_file:
      - shared.env
    environment:
      - EVENTSTORE_GOSSIP_SEED=172.30.240.11:2113,172.30.240.13:2113
      - EVENTSTORE_INT_IP=172.30.240.12
      - EVENTSTORE_CERTIFICATE_FILE=/certs/node2/node.crt
      - EVENTSTORE_CERTIFICATE_PRIVATE_KEY_FILE=/certs/node2/node.key
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=127.0.0.1
      - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2112
      - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=1112
    ports:
      - 1112:1113
      - 2112:2113
    networks:
      clusternetwork:
        ipv4_address: 172.30.240.12
    volumes:
      - ./certs:/certs
    restart: unless-stopped
    depends_on:
      - cert-gen

  esdb-node3:
    image: docker.pkg.github.com/eventstore/eventstore/eventstore:20.6.1-alpha.0.54-buster-slim
    env_file:
      - shared.env
    environment:
      - EVENTSTORE_GOSSIP_SEED=172.30.240.11:2113,172.30.240.12:2113
      - EVENTSTORE_INT_IP=172.30.240.13
      - EVENTSTORE_CERTIFICATE_FILE=/certs/node3/node.crt
      - EVENTSTORE_CERTIFICATE_PRIVATE_KEY_FILE=/certs/node3/node.key
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=127.0.0.1
      - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2113
      - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=1113
    ports:
      - 1113:1113
      - 2113:2113
    networks:
      clusternetwork:
        ipv4_address: 172.30.240.13
    volumes:
      - ./certs:/certs
    restart: unless-stopped
    depends_on:
      - cert-gen

networks:
  clusternetwork:
    name: eventstoredb.local
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.240.0/24